### ISSUE TITLE
Fix Footer Spelling

### ISSUE THREAD

**Issue by cat-kitty** [Zhou-Ziheng/VPSA#8]
Fix the VPSAAA to VPSA

**Comment by nexuspy** [comment]
can I work on this ?

**Comment by Paudzy** [comment]
> can I work on this ?

Dear Mister Pratik,

Thank you for your interest in taking over my issue. I appreciate your willingness to contribute, but I've decided to continue working on it myself. This particular task requires specialized knowledge and expertise that is unique to the Chief UI Designer role. It involves making critical design decisions and aligning them with our broader design strategy, which is part of my responsibility.

If you have any questions or would like to collaborate on a different project in the future, please feel free to reach out. I value your enthusiasm for our work.

Best regards,
Sam Paudel
Chief UI Designer

**Comment by Zhou-Ziheng** [comment]
I'll see if I can find another good beginner issue @nexuspy

**Comment by nexuspy** [comment]
> > can I work on this ?
> 
> Dear Mister Pratik,
> 
> Thank you for your interest in taking over my issue. I appreciate your willingness to contribute, but I've decided to continue working on it myself. This particular task requires specialized knowledge and expertise that is unique to the Chief UI Designer role. It involves making critical design decisions and aligning them with our broader design strategy, which is part of my responsibility.
> 
> If you have any questions or would like to collaborate on a different project in the future, please feel free to reach out. I value your enthusiasm for our work.
> 
> Best regards, Sam Paudel Chief UI Designer

I would love to work with team on future issues , thankyou @Paudzy @Zhou-Ziheng  !

**Comment by Paudzy** [comment]
ez. Merged to main.
